### ISSUE TITLE
please add English version

### ISSUE THREAD

**Issue by ttpro1995** [qiyuangong/Search_a_Paper_in_SEU_for_CSE#3]
I can google translate whole page. 
But I thing it would be better if you write in English.
Very helpful information. 

P/S: Look like you forgot http://gen.lib.rus.ec/ and https://sci-hub.tw/ 
This is where people with no access to school database get paper from.

**Comment by qiyuangong** [comment]
Thanks you for suggestion! :)

But, I don't think we need English version. As I have listed in references, there are lots of English blogs or  README about this topic. 

Meanwhile, I don't meant to survey all sources for Research paper. So, I will not list `lib.runs` and `sci-hub`.
