### ISSUE TITLE
结束语中的第五条Reference链接已失效

### ISSUE THREAD

**Issue by ChrisDoufu** [qiyuangong/Search_a_Paper_in_SEU_for_CSE#4]
感谢分享，此链接 [Effective Reading and Note-Taking](http://uaap.mit.edu/tutoring-support/study-tips/tooling-and-studying/tooling-and-studying-effective-reading-and-note-taking) 显示 404 Error

**Comment by qiyuangong** [comment]
多谢反馈，MIT的链接确实失效了，已替换为哥大的类似文章。同时增加了笔记管理的建议
